apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: jimpe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: impejonathan/brief-streamlit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: "http://api-service.jimpe.svc.cluster.local:8000/jimpe"
          livenessProbe:
            httpGet:
              path: /jimpe/_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /jimpe/_stcore/health
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3